import localFont from "next/font/local";
import "./globals.css";


const IBMFont = localFont({
  src: [
    {
      path: '/fonts/IBMPlexMono-Light.ttf',
      weight: '300',
      style: 'normal',
    },
    {
      path: '/fonts/IBMPlexMono-Regular.ttf',
      weight: 'normal',
      style: 'normal',
    },
    {
      path: '/fonts/IBMPlexMono-Medium.ttf',
      weight: '500',
      style: 'normal',
    },
    {
      path: '/fonts/IBMPlexMono-SemiBold.ttf',
      weight: '600',
      style: 'normal',
    },
    {
      path: '/fonts/IBMPlexMono-Bold.ttf',
      weight: '700',
      style: 'normal',
    }
  ]
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`bg-[#C4DACC] ${IBMFont.className}`}>{children}</body>
    </html>
  );
}
